name: wizard_router
description: A wizard router based on FlowBuilder.
homepage: https://github.com/jpnurmi/wizard_router
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flow_builder: ^0.0.3
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
